version: "3"
services:
  backend:
    build: .
    command: sh -c "python -m uvicorn main:app --port=8000 --host=0.0.0.0"
    env_file:
      - .env.staging
    ports:
      - 8081:8000
    volumes:
      - .:/app

